[package]
name = "minls"
version = "0.1.0"
authors = ["Demon_Munchies <hirtquinn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
